### ISSUE TITLE
beta values

### ISSUE THREAD

**Issue by MiMinambres** [Gregor-Mendel-Institute/MultLocMixMod#2]
Hello, we are using the MultLocMixMod package to perform GWAS analysis. We would like to get the beta values but in the output dataframe it is not available. Is there an easy way to get the beta values? I apologyze in advance if there is an obvious solution.

**Comment by visegura** [comment]
Hi,
The betas are only available for the SNP selected as cofactors at each forward step or in the best model according to the EBIC or mbonf criteria.
Consider that the output list of mlmm function is stored in the object `mygwas`, then the betas for the cofactors in the best model according to:
- EBIC are in the first column ("estimate") of this table: `mygwas$opt_extBIC$coef`
- mbonf are in the first column ("estimate") of this table: `mygwas$opt_mbonf$coef`
For a given forward step (i) the same table of coefficients can be obtained like this: `mygwas$pval_step[[i]]$coef`
Note that the first row of such coefficient tables contains the estimates for the intercept.
The betas for the other SNPs (not selected as cofactors) are not stored and thus not available in the output.
Hope it helps,
Vincent

**Comment by MiMinambres** [comment]
Hi Vincent,
thank you very much for your kind and fast response! Your clear explanation
is very usefull for us, as we are trying to perform EMMAX and MLMM and it
is quite difficult for us sometimes.

Regards,

Miguel

2018-03-04 16:14 GMT+01:00 Vincent Segura <notifications@github.com>:
