### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by gpcr** [Gregor-Mendel-Institute/MultLocMixMod#3]
> library(devtools); install_github("Gregor-Mendel-Institute/MultLocMixMod")
Installation failed: Could not resolve host: raw.githubusercontent.com

**Comment by visegura** [comment]
I have just checked your issue and could not reproduce the error on my pc. Could you please try it again?

**Comment by gpcr** [comment]
After few attempts, some how I was able to install it today using same commands
Thanks
