### ISSUE TITLE
 how to calculate the phenotypic variation explained by significant SNPs

### ISSUE THREAD

**Issue by congzhouczcz** [Gregor-Mendel-Institute/MultLocMixMod#8]
Hi, Vincent:
  I used the package ‘mlmm.gwas’ (https://rdrr.io/cran/mlmm.gwas/) which estimate the effect of selected SNPs.
  I'm curious  how to calculate the phenotypic variation explained by significant SNPs in a particular region as mentioned in your paper. For example,  'To further investigate the associations in this particular region, we applied our method locally, using only the 508 SNPs located within 100 kb of the gene. Using EBIC six SNPs were included in the model, all within 25 kb of AtHKT1;1,which explained 52.6% of the phenotypic variation'
  I tried to install MultLocMixMod and want to follow the vignettes but it is difficult to install without errors in my PC. 
. Could you give some guidance on how to  calculate the phenotypic variation explained by significant SNPs?
  Thank you very much !

Sincerely,
Cong

**Comment by visegura** [comment]
Dear Cong,

The easier is probably to use the package MultLocMixMod which provides automatically an estimate of the proportion of variance explained by cofactors at each step.

To install the package you should follow these steps :
1. Install the package `emma` but not the one from CRAN. For this use this command:
`install.packages("https://github.com/Gregor-Mendel-Institute/mlmm/files/1356516/emma_1.1.2.tar.gz", repos = NULL)`
2. Install and load the package `devtools`:
`install.packages("devtools"); library(devtools)`
3. Install the package `mlmm`:
`install_github("Gregor-Mendel-Institute/MultLocMixMod")`
At this step you might have a message asking if you wish to update some packages, better to reply "no" to make sure the installation of `mlmm` succeeds.

Hope it helps.
Best regards,
Vincent
