### ISSUE TITLE
Exporting Results

### ISSUE THREAD

**Issue by MuBulut** [Gregor-Mendel-Institute/MultLocMixMod#9]
Hi,
I adjusted my data accordingly and run your "code_mlmm.R" script, which runs the whole pipeline.
I was just wondering, if there is a way/command to export all the generated data/figures to a defined path?
Thanks in advance.
Mustafa

**Comment by visegura** [comment]
Dear Mustufa,
You could for example use the r function `pdf` to export all graphs into a pdf file. 
If you wish to save all results including data and figures together with the code and comments, I would recommend using rmarkdown which enables you to generate a full report of your analysis.
Hope it helps,
Best regards,
Vincent
